# SPDX-FileCopyrightText: Copyright 2020-2024, Contributors to CICD
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/cicd
# SPDX-License-Identifier: Apache-2.0

# These settings are synced to GitHub by https://probot.github.io/apps/settings/

repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # The name of the repository. Changing this will rename the repository
  # :tyranno: ${project.name}
  name: cicd

  # A short description of the repository that will show up on GitHub
  # :tyranno: ${project.description}
  description: CI/CD example

  # :tyranno: ${project.urls.main}
  homepage: https://github.com/dmyersturnbull/cicd

  # :tyranno: topics: ${project.keywords}
  topics: ci, cd, ci/cd

  private: false

  has_issues: true
  has_projects: true
  has_discussions: true
  has_downloads: true
  has_wiki: false

  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true

  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

# Adapted from https://opensource.creativecommons.org/contributing-code/repo-labels/
# https://gitmoji.dev/
# https://seantrane.com/posts/logical-colorful-github-labels-18230/
# and https://github.com/pvdlg/conventional-changelog-metahub
labels:
  - name: "breaking"
    description: "ğŸ’¥ Breaking change"
    color: "#000000"
  - name: "help needed"
    description: "ğŸ‘‹ Help needed"
    color: "#40f040"
  - name: "bookmark"
    description: "ğŸ”– Important for reference"
    color: "#ffff44"
  - name: "changelog: include"
    description: "ğŸ”” Always include in the changelog"
    color: "#ffe6e6"
  - name: "changelog: exclude"
    description: "ğŸ”• Always omit from the changelog"
    color: "#eeeeee"
  - name: "type: drop"
    description: "âŒ Removal of a feature"
    color: "#440000"
  - name: "type: feature"
    description: "âœ¨ Addition or modification of a feature"
    color: "#000060"
  - name: "type: security"
    description: "ğŸ”’ï¸ Vulnerability fix/mitigation or hardening"
    color: "#000060"
  - name: "type: deprecation"
    description: "ğŸ—‘ï¸ Deprecation of a feature or component"
    color: "#000000"
  - name: "type: fix"
    description: "ğŸ› Bug fix, excluding security vulnerabilities"
    color: "#000060"
  - name: "type: performance"
    description: "âš¡ï¸ Code change that improves performance"
    color: "#000060"
  - name: "type: build"
    description: "ğŸ”§ Change to the build system or external dependencies"
    color: "#000060"
  - name: "type: docs"
    description: "ğŸ“ Change to documentation only"
    color: "#000060"
  - name: "type: refactor"
    description: "â™»ï¸ Code change that neither fixes a bug nor adds or modifies a feature"
    color: "#000060"
  - name: "type: test"
    description: "ğŸš¨ Addition or modification of tests"
    color: "#000060"
  - name: "type: cicd"
    description: "âš™ï¸ Change to continuous integration and deployment (CI/CD)"
    color: "#000060"
  - name: "type: style"
    description: "ğŸ¨ Code change that does not affect the meaning of the code"
    color: "#000060"
  - name: "type: chore"
    description: "ï¸ğŸ§¹ Other type of change"
    color: "#000060"
  - name: "priority: critical"
    description: "ğŸŸ¥ Must be fixed ASAP"
    color: "#ff6600"
  - name: "priority: high"
    description: "ğŸŸ§ Stalls work on the project or its dependents"
    color: "#cc9911"
  - name: " priority: medium"
    description: "ğŸŸ¨ Does not block release/milestone but should be prioritized"
    color: "#cccc11"
  - name: "priority: low"
    description: "ğŸŸ© Does not block release/milestone and can be done at any time"
    color: "#99dd00"
  - name: "state: ready for dev"
    description: "ğŸ Ready for work"
    color: "#cccccc"
  - name: "state: blocked"
    description: "ğŸš§ Blocked by another issue"
    color: "#999999"
  - name: "state: needs details"
    description: "ğŸ·ï¸ Needs more details before work can begin"
    color: "#666666"
  - name: "state: rejected"
    description: "âœ–ï¸ Will not be worked on"
    color: "#eeeeee"
  - name: "state: awaiting triage"
    description: "ğŸš¦ Awaiting triage"
    color: "#444444"
  - name: "effort: 1"
    description: "1ï¸âƒ£ Easy (t < 1 hr)"
    color: "#300040"
  - name: "effort: 2"
    description: "2ï¸âƒ£ Moderate (1 hr â‰¤ t < 4 hr)"
    color: "#600040"
  - name: "effort: 3"
    description: "3ï¸âƒ£ï¸ Hard (â‰¥ 4 hours)"
    color: "#900040"
  - name: "effort: multipart"
    description: "*ï¸âƒ£ Organizes multiple sub-issues"
    color: "#900040"
  - name: "scope: plugin"
    description: "ğŸ§© Plugins"
    color: "#009000"
  - name: "scope: i18n"
    description: "ğŸŒ Internationalization"
    color: "#009000"

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: false
      required_linear_history: true
      restrictions: null
