# SPDX-FileCopyrightText: Copyright 2020-2023, Contributors to CICD
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/cicd
# SPDX-License-Identifier: Apache-2.0

name: Pull request comment

on:
  issue_comment:
    types: [created, edited, deleted]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read
  statuses: read
  actions: read
  security-events: write
  pull-requests: write
  issues: write

jobs:
  get-branch-name:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/please-test') }}
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.branch_name.outputs.staging_branch }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get staging branch name
        id: branch_name
        run: echo "staging_branch=$(git for-each-ref --format='%(refname:short)' refs/heads/staging*)" >> $GITHUB_OUTPUT

  test:
    name: Test
    needs: [get-branch-name]
    uses: ./.github/workflows/_test.yaml
    with:
      ref: ${{ needs.get-branch-name.outputs.ref }}
    secrets: inherit
